# -*- coding: utf-8 -*-
"""Kopie sešitu warspotting_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r2WcKfDOC4qU86SP_zLa-yKgMnAbscfu
"""

import os
import time
from datetime import date, timedelta

import requests
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates


# ============================================================
# WARSPOTTING – AUTOMATED DATA ANALYSIS DASHBOARD
# ============================================================

BASE_URL = "https://ukr.warspotting.net/api/losses/russia"

RAW_FILE = "warspotting_raw_2026.csv"
WEEKLY_FILE = "weekly_losses_2026.csv"
DASHBOARD_FILE = "dashboard.png"

START_DATE = date(2026, 1, 1)


# ============================================================
# API SETTINGS
# ============================================================

HEADERS = {
    "User-Agent": "WarSpotting-Analytics-Dashboard/1.0"
}

MAX_RETRIES = 5
RETRY_DELAY = 5


# ============================================================
# API REQUEST
# ============================================================

def get_day_data(target_date):
    """
    Download WarSpotting losses for one day.
    Includes retry logic for temporary API errors.
    """

    date_string = target_date.strftime("%Y-%m-%d")

    url = f"{BASE_URL}/{date_string}/1/"

    for attempt in range(1, MAX_RETRIES + 1):

        try:

            response = requests.get(
                url,
                headers=HEADERS,
                timeout=30
            )

            if response.status_code == 200:

                data = response.json()

                if isinstance(data, dict):

                    return data.get("losses", [])

                return []

            if response.status_code in [
                429,
                500,
                502,
                503,
                504,
                520
            ]:

                wait = RETRY_DELAY * attempt

                print(
                    f"HTTP {response.status_code} | "
                    f"{date_string} | "
                    f"retry {attempt}/{MAX_RETRIES} "
                    f"in {wait}s"
                )

                time.sleep(wait)

                continue

            print(
                f"HTTP {response.status_code} | "
                f"{date_string}"
            )

            return []

        except requests.RequestException as error:

            wait = RETRY_DELAY * attempt

            print(
                f"REQUEST ERROR | "
                f"{date_string} | "
                f"retry {attempt}/{MAX_RETRIES} "
                f"in {wait}s"
            )

            time.sleep(wait)

    print(
        f"FAILED: {date_string}"
    )

    return []


# ============================================================
# LOAD EXISTING RAW DATA
# ============================================================

def load_existing_data():

    if not os.path.exists(RAW_FILE):

        print()
        print("=" * 60)
        print("NO EXISTING DATASET")
        print("=" * 60)

        return pd.DataFrame()

    print()
    print("=" * 60)
    print("EXISTING DATASET")
    print("=" * 60)

    df = pd.read_csv(RAW_FILE)

    df["date"] = pd.to_datetime(
        df["date"]
    )

    print(
        f"Records loaded : {len(df):,}"
    )

    if len(df) > 0:

        print(
            f"First date     : "
            f"{df['date'].min().date()}"
        )

        print(
            f"Last date      : "
            f"{df['date'].max().date()}"
        )

    return df


# ============================================================
# UPDATE RAW DATA
# ============================================================

def update_raw_data(df):

    yesterday = (
        pd.Timestamp.today().normalize()
        - pd.Timedelta(days=1)
    )

    # --------------------------------------------------------
    # Determine first date that needs to be downloaded.
    # --------------------------------------------------------

    if df.empty:

        start_date = pd.Timestamp(
            START_DATE
        )

    else:

        last_date = df["date"].max()

        start_date = (
            last_date
            + pd.Timedelta(days=1)
        )

    # --------------------------------------------------------
    # Dataset already up to date.
    # --------------------------------------------------------

    if start_date > yesterday:

        print()
        print(
            "RAW DATA ALREADY UP TO DATE"
        )

        return df

    print()
    print("=" * 60)
    print("DOWNLOADING NEW DATA")
    print("=" * 60)

    print(
        f"From: {start_date.date()}"
    )

    print(
        f"To:   {yesterday.date()}"
    )

    new_records = []

    current_date = start_date

    # --------------------------------------------------------
    # Download one day at a time.
    # --------------------------------------------------------

    while current_date <= yesterday:

        records = get_day_data(
            current_date.date()
        )

        print(
            f"{current_date.date()} | "
            f"records: {len(records)}"
        )

        new_records.extend(
            records
        )

        current_date += pd.Timedelta(
            days=1
        )

        # Prevent excessive API requests.
        time.sleep(1.5)

    # --------------------------------------------------------
    # Add new data to existing dataset.
    # --------------------------------------------------------

    if new_records:

        new_df = pd.DataFrame(
            new_records
        )

        new_df["date"] = pd.to_datetime(
            new_df["date"]
        )

        if df.empty:

            df = new_df

        else:

            df = pd.concat(
                [df, new_df],
                ignore_index=True
            )

        # ----------------------------------------------------
        # Remove duplicate equipment records.
        # ----------------------------------------------------

        before = len(df)

        df = df.drop_duplicates(
            subset=["id"],
            keep="last"
        )

        duplicates_removed = (
            before - len(df)
        )

        # ----------------------------------------------------
        # Sort chronologically.
        # ----------------------------------------------------

        df = df.sort_values(
            ["date", "id"]
        ).reset_index(
            drop=True
        )

        # ----------------------------------------------------
        # Save RAW dataset.
        # ----------------------------------------------------

        df.to_csv(
            RAW_FILE,
            index=False
        )

        print()
        print(
            f"New records added : "
            f"{len(new_records):,}"
        )

        print(
            f"Duplicates removed: "
            f"{duplicates_removed:,}"
        )

        print(
            f"Total records     : "
            f"{len(df):,}"
        )

        print(
            f"RAW DATA SAVED    : "
            f"{RAW_FILE}"
        )

    else:

        print()
        print(
            "No new records downloaded."
        )

    return df


# ============================================================
# DATA VALIDATION
# ============================================================

def validate_data(df):

    print()
    print("=" * 60)
    print("DATA VALIDATION")
    print("=" * 60)

    if df.empty:

        print(
            "ERROR: Dataset is empty."
        )

        return False

    required_columns = [
        "id",
        "type",
        "model",
        "status",
        "lost_by",
        "date"
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing_columns:

        print(
            "Missing columns:"
        )

        print(
            missing_columns
        )

        return False

    duplicate_ids = (
        df["id"]
        .duplicated()
        .sum()
    )

    print(
        f"Records       : "
        f"{len(df):,}"
    )

    print(
        f"Unique IDs    : "
        f"{df['id'].nunique():,}"
    )

    print(
        f"Duplicate IDs : "
        f"{duplicate_ids:,}"
    )

    print(
        f"First date    : "
        f"{df['date'].min().date()}"
    )

    print(
        f"Last date     : "
        f"{df['date'].max().date()}"
    )

    # --------------------------------------------------------
    # Validation result.
    # --------------------------------------------------------

    if duplicate_ids > 0:

        print()
        print(
            "VALIDATION: FAILED"
        )

        return False

    print()
    print(
        "VALIDATION: OK"
    )

    return True


# ============================================================
# WEEKLY ANALYSIS
# ============================================================

def create_weekly_dataset(df):

    print()
    print("=" * 60)
    print("WEEKLY ANALYSIS")
    print("=" * 60)

    data = df.copy()

    data["date"] = pd.to_datetime(
        data["date"]
    )

    # --------------------------------------------------------
    # Monday = beginning of analytical week.
    # --------------------------------------------------------

    data["week"] = (
        data["date"]
        - pd.to_timedelta(
            data["date"].dt.weekday,
            unit="D"
        )
    )

    # --------------------------------------------------------
    # Count records per week.
    # --------------------------------------------------------

    weekly = (
        data
        .groupby("week")
        .size()
        .reset_index(
            name="weekly_losses"
        )
    )

    weekly = weekly.sort_values(
        "week"
    ).reset_index(
        drop=True
    )

    # --------------------------------------------------------
    # Cumulative losses.
    # --------------------------------------------------------

    weekly["cumulative_losses"] = (
        weekly["weekly_losses"]
        .cumsum()
    )

    # --------------------------------------------------------
    # Four-week moving average.
    # --------------------------------------------------------

    weekly["rolling_4_week_avg"] = (
        weekly["weekly_losses"]
        .rolling(
            window=4,
            min_periods=1
        )
        .mean()
    )

    # --------------------------------------------------------
    # Save analytical dataset.
    # --------------------------------------------------------

    weekly.to_csv(
        WEEKLY_FILE,
        index=False
    )

    print(
        f"Number of weeks : "
        f"{len(weekly)}"
    )

    print(
        f"First week      : "
        f"{weekly['week'].min().date()}"
    )

    print(
        f"Last week       : "
        f"{weekly['week'].max().date()}"
    )

    print()
    print(
        "Last 10 weeks:"
    )

    print(
        weekly.tail(10).to_string(
            index=False
        )
    )

    print()
    print(
        f"WEEKLY DATA SAVED: "
        f"{WEEKLY_FILE}"
    )

    return weekly


# ============================================================
# DASHBOARD
# ============================================================

def create_dashboard(df, weekly):

    # --------------------------------------------------------
    # KPI calculations
    # --------------------------------------------------------

    total_losses = len(df)

    this_week = int(
        weekly.iloc[-1][
            "weekly_losses"
        ]
    )

    four_week_avg = float(
        weekly.iloc[-1][
            "rolling_4_week_avg"
        ]
    )

    # --------------------------------------------------------
    # Data quality check.
    # --------------------------------------------------------

    weekly_total = int(
        weekly["weekly_losses"].sum()
    )

    data_check = (
        total_losses == weekly_total
    )

    # --------------------------------------------------------
    # Console summary.
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("WARSPOTTING DASHBOARD")
    print("=" * 60)

    print(
        f"TOTAL LOSSES : "
        f"{total_losses:,}"
    )

    print(
        f"THIS WEEK    : "
        f"{this_week}"
    )

    print(
        f"4-WEEK AVG   : "
        f"{four_week_avg:.1f}"
    )

    print(
        f"DATA CHECK   : "
        f"{'OK' if data_check else 'ERROR'}"
    )

    if not data_check:

        raise ValueError(
            "Weekly totals do not match "
            "RAW dataset."
        )

    # ========================================================
    # FIGURE
    # ========================================================

    fig = plt.figure(
        figsize=(16, 9)
    )

    # --------------------------------------------------------
    # Dashboard title
    # --------------------------------------------------------

    fig.text(
        0.055,
        0.955,
        "WarSpotting – Russian Equipment Losses Dashboard",
        fontsize=24,
        fontweight="bold",
        ha="left"
    )

    # ========================================================
    # KPI CARDS
    # ========================================================

    cards = [
        (
            0.055,
            "TOTAL LOSSES",
            f"{total_losses:,}"
        ),
        (
            0.375,
            "THIS WEEK",
            f"{this_week:,}"
        ),
        (
            0.695,
            "4-WEEK AVG",
            f"{four_week_avg:.1f}"
        )
    ]

    for x, label, value in cards:

        ax_card = fig.add_axes(
            [
                x,
                0.72,
                0.27,
                0.15
            ]
        )

        ax_card.set_xticks([])
        ax_card.set_yticks([])

        for spine in ax_card.spines.values():

            spine.set_visible(True)
            spine.set_linewidth(1)

        ax_card.text(
            0.06,
            0.70,
            label,
            fontsize=12,
            fontweight="bold",
            transform=ax_card.transAxes
        )

        ax_card.text(
            0.06,
            0.20,
            value,
            fontsize=28,
            fontweight="bold",
            transform=ax_card.transAxes
        )

    # ========================================================
    # MAIN CHART
    # ========================================================

    ax = fig.add_axes(
        [
            0.055,
            0.12,
            0.90,
            0.50
        ]
    )

    weeks = weekly["week"]

    weekly_losses = (
        weekly["weekly_losses"]
    )

    cumulative_losses = (
        weekly["cumulative_losses"]
    )

    # --------------------------------------------------------
    # WEEKLY LOSSES – BARS
    # --------------------------------------------------------

    ax.bar(
        weeks,
        weekly_losses,
        width=5.5,
        alpha=0.85,
        label="Weekly losses"
    )

    # --------------------------------------------------------
    # CUMULATIVE LOSSES – LINE
    # --------------------------------------------------------

    ax2 = ax.twinx()

    ax2.plot(
        weeks,
        cumulative_losses,
        linewidth=1.5,
        alpha=0.75,
        label="Cumulative losses"
    )

    # --------------------------------------------------------
    # Titles
    # --------------------------------------------------------

    ax.set_title(
        "Russian Equipment Losses Over Time",
        fontsize=18,
        fontweight="bold",
        loc="left",
        pad=14
    )

    # --------------------------------------------------------
    # Axis labels
    # --------------------------------------------------------

    ax.set_ylabel(
        "Weekly recorded losses",
        fontsize=11
    )

    ax2.set_ylabel(
        "Cumulative recorded losses",
        fontsize=11
    )

    ax.set_xlabel(
        "Week",
        fontsize=11
    )

    # ========================================================
    # ADAPTIVE Y AXIS
    # ========================================================

    max_weekly = (
        weekly_losses.max()
    )

    y_max = max(
        10,
        ((max_weekly * 1.15) // 5 + 1) * 5
    )

    ax.set_ylim(
        0,
        y_max
    )

    # ========================================================
    # ADAPTIVE X AXIS
    #
    # Every bar = one week.
    # Major labels approximately every 2 months.
    # ========================================================

    ax.xaxis.set_major_locator(
        mdates.MonthLocator(
            interval=2
        )
    )

    ax.xaxis.set_major_formatter(
        mdates.DateFormatter(
            "%b %Y"
        )
    )

    # --------------------------------------------------------
    # X-axis limits
    # --------------------------------------------------------

    ax.set_xlim(
        weeks.min()
        - pd.Timedelta(days=7),

        weeks.max()
        + pd.Timedelta(days=14)
    )

    # --------------------------------------------------------
    # Grid
    # --------------------------------------------------------

    ax.grid(
        axis="y",
        alpha=0.25
    )

    ax.set_axisbelow(True)

    # --------------------------------------------------------
    # Remove unnecessary borders.
    # --------------------------------------------------------

    ax.spines["top"].set_visible(
        False
    )

    ax2.spines["top"].set_visible(
        False
    )

    # ========================================================
    # LEGEND
    # ========================================================

    bars, labels = ax.get_legend_handles_labels()

    lines, line_labels = (
        ax2.get_legend_handles_labels()
    )

    ax.legend(
        bars + lines,
        labels + line_labels,
        loc="upper left"
    )

    # ========================================================
    # SAVE DASHBOARD
    # ========================================================

    plt.savefig(
        DASHBOARD_FILE,
        dpi=150,
        bbox_inches="tight"
    )

    plt.close(fig)

    print()
    print("=" * 60)
    print("DASHBOARD CREATED")
    print("=" * 60)

    print(
        f"File: {DASHBOARD_FILE}"
    )

    return (
        total_losses,
        this_week,
        four_week_avg
    )


# ============================================================
# MAIN PIPELINE
# ============================================================

def main():

    print()
    print("=" * 60)
    print("WARSPOTTING AUTOMATED PIPELINE")
    print("=" * 60)

    # --------------------------------------------------------
    # 1. Load existing RAW dataset.
    # --------------------------------------------------------

    df = load_existing_data()

    # --------------------------------------------------------
    # 2. Download only new data.
    # --------------------------------------------------------

    df = update_raw_data(
        df
    )

    # --------------------------------------------------------
    # 3. Validate RAW dataset.
    # --------------------------------------------------------

    if not validate_data(df):

        print()
        print(
            "PIPELINE STOPPED."
        )

        return

    # --------------------------------------------------------
    # 4. Create weekly analytical dataset.
    # --------------------------------------------------------

    weekly = create_weekly_dataset(
        df
    )

    # --------------------------------------------------------
    # 5. Create dashboard.
    # --------------------------------------------------------

    create_dashboard(
        df,
        weekly
    )

    # --------------------------------------------------------
    # 6. Final status.
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("PIPELINE COMPLETE")
    print("=" * 60)

    print(
        "STATUS: OK"
    )


# ============================================================
# SCRIPT ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()