from pathlib import Path
import json

import pandas as pd
import streamlit as st


# ---------------------------------------------------------
# Page configuration
# ---------------------------------------------------------
st.set_page_config(
    page_title="WarSpotting Dashboard",
    page_icon="📊",
    layout="wide",
)


# ---------------------------------------------------------
# File paths
# ---------------------------------------------------------
WEEKLY_FILE = Path("weekly_equipment_losses.csv")
QUALITY_FILE = Path("data_quality.json")
HTML_FILE = Path("equipment_weekly.html")


# ---------------------------------------------------------
# Load weekly analytical data
# ---------------------------------------------------------
def load_weekly_data():
    if not WEEKLY_FILE.exists():
        raise FileNotFoundError(
            f"Required file not found: {WEEKLY_FILE}"
        )

    df = pd.read_csv(WEEKLY_FILE)

    required_columns = {"week", "type", "losses"}
    missing_columns = required_columns - set(df.columns)

    if missing_columns:
        raise ValueError(
            "weekly_equipment_losses.csv is missing required "
            f"columns: {', '.join(sorted(missing_columns))}"
        )

    df["week"] = pd.to_datetime(df["week"], errors="coerce")
    df["losses"] = pd.to_numeric(df["losses"], errors="coerce")

    if df["week"].isna().any():
        raise ValueError("Invalid week values found.")

    if df["losses"].isna().any():
        raise ValueError("Invalid losses values found.")

    return df


# ---------------------------------------------------------
# Load data quality information
# ---------------------------------------------------------
def load_quality_data():
    if not QUALITY_FILE.exists():
        raise FileNotFoundError(
            f"Required file not found: {QUALITY_FILE}"
        )

    with QUALITY_FILE.open("r", encoding="utf-8") as file:
        return json.load(file)


# ---------------------------------------------------------
# Load original interactive Plotly HTML
# ---------------------------------------------------------
def load_plotly_html():
    if not HTML_FILE.exists():
        raise FileNotFoundError(
            f"Required file not found: {HTML_FILE}"
        )

    return HTML_FILE.read_text(encoding="utf-8")


# ---------------------------------------------------------
# Load data
# ---------------------------------------------------------
try:
    weekly = load_weekly_data()
    quality = load_quality_data()
    plotly_html = load_plotly_html()

except Exception as exc:
    st.error("The dashboard could not load its data.")
    st.code(str(exc))
    st.stop()


# ---------------------------------------------------------
# Basic quality values
# ---------------------------------------------------------
validation_status = str(
    quality.get("validation_status", "UNKNOWN")
).upper()

raw_records = quality.get("raw_records", "—")
analytical_records = quality.get("analytical_records", "—")
excluded_records = quality.get("excluded_lost_by", "—")
weekly_rows = quality.get("weekly_rows", len(weekly))

unique_weeks = weekly["week"].nunique()
total_losses = int(weekly["losses"].sum())
category_count = weekly["type"].nunique(dropna=True)

average_weekly_losses = (
    total_losses / unique_weeks if unique_weeks else 0
)


# ---------------------------------------------------------
# Header
# ---------------------------------------------------------
st.title("Russian Equipment Losses — Weekly")
st.caption(
    "Documented Russian equipment losses based on WarSpotting data."
)


# ---------------------------------------------------------
# KPI row
# ---------------------------------------------------------
kpi1, kpi2, kpi3, kpi4 = st.columns(4)

with kpi1:
    st.metric(
        "Documented losses",
        f"{total_losses:,}",
    )

with kpi2:
    st.metric(
        "Average per week",
        f"{average_weekly_losses:,.1f}",
    )

with kpi3:
    st.metric(
        "Equipment categories",
        f"{category_count:,}",
    )

with kpi4:
    st.metric(
        "Data quality",
        validation_status,
    )


# ---------------------------------------------------------
# Data quality
# ---------------------------------------------------------
st.subheader("Data quality")

quality_col1, quality_col2, quality_col3, quality_col4 = st.columns(4)

with quality_col1:
    st.write("**Status**")
    st.write(validation_status)

with quality_col2:
    st.write("**Last update (UTC)**")
    st.write(quality.get("last_update", "—"))

with quality_col3:
    st.write("**Raw / analytical**")
    st.write(f"{raw_records:,} / {analytical_records:,}")

with quality_col4:
    st.write("**Excluded records**")
    st.write(f"{excluded_records:,}")


# ---------------------------------------------------------
# Original Plotly HTML component
#
# This is a performance test and a functional-preservation
# test. It reuses the exact HTML generated by
# equipment_plot.py, including its custom tooltip,
# dotted hover line, selected-week opacity and Equipment
# panel.
# ---------------------------------------------------------
st.subheader("Equipment losses by week")

st.html(
    Path(HTML_FILE),
    unsafe_allow_javascript=True,
)


# ---------------------------------------------------------
# Technical data
# ---------------------------------------------------------
with st.expander("Technical data"):
    st.write(
        f"Source dataset: `weekly_equipment_losses.csv`"
    )
    st.write(f"Rows: **{len(weekly):,}**")
    st.write(f"Weeks: **{unique_weeks:,}**")
    st.write(f"Equipment categories: **{category_count:,}**")
    st.write(
        f"Coverage: **{weekly['week'].min().date()} – "
        f"{weekly['week'].max().date()}**"
    )


# ---------------------------------------------------------
# Methodology
# ---------------------------------------------------------
with st.expander("Methodology and limitations"):
    st.write(
        "The dashboard uses documented WarSpotting equipment-loss "
        "records aggregated by week and equipment category."
    )
    st.write(
        "The dataset represents documented/visually confirmed records "
        "and should not be interpreted as a complete count of actual "
        "military losses."
    )
